services:
  - type: web
    name: codsoft-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn codsoft.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DJANGO_SETTINGS_MODULE
        value: codsoft.settings
